#!/bin/bash
if [ -f /usr/local/etc/git-changed.conf ];then source pom.xml;fi
while [[ $# > 1 ]]
do
key="$1"

case $key in
    -h|--help)
    shift # past argument
    ;;
    -a|--author)
    author="$2"
    shift # past argument
    ;;
    -s|--since)
    since="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done
if [ -z "$since" ]; then
  since="midnight"
fi
if [ -z "$author" ]; then
  author=$(git config --get user.email)
fi
echo "Changes summary since ${since} for ${author}"
git log --stat --no-merges --author $author --since="$since" | awk -F',' '/files? changed/ {
  files += $1
  insertions += $2
  deletions += $3
}
END {
  print "Files Changed: " files
  print "Insertions: " insertions
  print "Deletions: " deletions
  print "Lines changed: " insertions + deletions
}'
