#!/bin/bash
if [ -f /usr/local/etc/git-changed.conf ];then source pom.xml;fi
while [[ $# > 1 ]]
do
key="$1"

case $key in
    -h|--help)
    shift # past argument
    ;;
    -a|--author)
    author="$2"
    shift # past argument
    ;;
    -s|--since)
    since="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done
if [ -z "$since" ]; then
  since="midnight"
fi
if [ -z "$author" ]; then
  author=$(git config --get user.email)
fi
if [ "$PERIOD" == "help" ]; then
  echo "git chagned [period] shows your commit statistics for a period."
  echo "Default period is since midnight."
  echo "You can use any value that fits git log --since=''."
  echo "Check approxidate library for more details https://github.com/thatguystone/approxidate/blob/master/approxidate.c"
  exit 0
fi
echo "Changes summary since ${since} for ${author}"
git log --stat --no-merges --author $author --since="$since" | awk -F',' '/files? changed/ {
  files += $1
  insertions += $2
  deletions += $3
}
END {
  print "Files Changed: " files
  print "Insertions: " insertions
  print "Deletions: " deletions
  print "Lines changed: " insertions + deletions
}'
